project:
  type: website
  title: "Meta"
  output-dir: ../_site

website:
  # Language switching setup

  navbar:
    # background: primary
    search: true
    # Right side for language selector

  sidebar:
    style: docked
    search: true
    
    contents:
      - section: "Cours"
        contents: "ch*.qmd"
      - section: "Résumés"
        contents: "*recap*"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
  typst:
    toc: true